[micronaut]
[micronaut.server]
port = "@app.port@"

[jackson]
[jackson.deserialization]
FAIL_ON_UNKNOWN_PROPERTIES = false

[jpa]
[jpa.default.properties.hibernate]
show_sql = true
format_sql = true
cdi.extensions = true
