[micronaut]
environments = "${MICRONAUT_ENVIRONMENTS}"
[micronaut.application]
name = "geom-app-admin"
[micronaut.server]
port = "@app.port@"

[jackson]
date-format = "yyyy-MM-dd HH:mm:ss"
[jackson.deserialization]
FAIL_ON_UNKNOWN_PROPERTIES = false

[jpa]
[jpa.default.properties.hibernate]
show_sql = true
format_sql = true
cdi.extensions = true

[liquibase]
[liquibase.datasources]
[liquibase.datasources.default]
change-log = "classpath:db/liquibase-changelog.xml"
tag = "@project.version@"

[geom]
id-generator = "${GEOM_ID_GENERATOR:snowflake}"
[geom.jwt]
issuer = "${GEOM_JWT_ISSUER:xezzon.github.io}"

[sa-token]
token-name = "X-SESSION-ID"
token-style = "tik"
