[micronaut]
environments = "${MICRONAUT_ENVIRONMENTS}"
[micronaut.application]
name = "geom-app-admin"

[geom]
id-generator = "${GEOM_ID_GENERATOR:snowflake}"
[geom.jwt]
issuer = "${GEOM_JWT_ISSUER:xezzon.github.io}"

[sa-token]
token-name = "X-SESSION-ID"
token-style = "tik"
